name: dat_ve_xem_phim
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  carousel_slider: ^5.0.0
  cached_network_image: ^3.2.3
  google_fonts: ^6.1.0
  geolocator: ^10.1.0
  url_launcher: ^6.3.2
  youtube_player_flutter: ^9.1.3
  vnpay_flutter: ^2.0.0
  webview_flutter: ^4.13.0
  crypto: ^3.0.3
  firebase_core: ^4.2.0
  firebase_database: ^12.0.3
  firebase_auth: ^6.1.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
